nginx:
    build: ./
    dockerfile: Dockerfile
    volumes:
        - ~/Projects/default_environment:/var/www/html
    ports:
        - "80:80"
        - "443:443"
    links:
        - fpm
fpm:
    image: php:7.1-fpm
    volumes:
        - ~/Projects/default_environment:/var/www/html
    links:
        - mysql
mysql:
    image: mariadb:latest
    environment:
        - MYSQL_ROOT_PASSWORD=test
    ports:
        - "3306:3306"
